Add support for request signal on BOStrab:f signals
OpenRailwayMap/OpenRailwayMap-CartoCSS pull request #106
Opened 2023-10-28 22:24 UTC by besentv

The approach is pretty terrible, so I'm open for improvements.

Example rendering in Karlsruhe around Durlacher Tor.

2023-10-31 00:21 UTC, besentv commented
Mhm, I just realized that many cities actually have the A as the very first light, for example:
- Karlsruhe
- Mannheim
- Mainz
- Kassel
- Leipzig
However these have it at the bottom:
- Nürnberg
- Erfurt

2023-12-02 16:45 UTC, besentv commented
I think i found a better way of implementing this, using layer instances.

2023-12-29 16:03 UTC, Nakaner requested changes
I would like to ask to start rendering St 9 signals on zoom level 16, not 15 like the F signals. Enlarging the signals by 50% hides more other signals.

Please fix the syntax as well (see inline comment).

Zoom level 15:

![kronenplatz-z15](https://github.com/OpenRailwayMap/OpenRailwayMap-CartoCSS/assets/3611273/e5f908e9-3d10-45eb-8b7a-728281bd12f8)

Zoom level 16:

![kronenplatz-z16](https://github.com/OpenRailwayMap/OpenRailwayMap-CartoCSS/assets/3611273/121a8947-057b-4ccd-af7a-497866c9de9a)

2024-02-25 09:00 UTC, bjoernma commented
As I couldnt find St9 in BOStrab it seems that its in most cities more of a [railway:signal:main:PT_priority=requested;off](https://wiki.openstreetmap.org/wiki/DE:OpenRailwayMap/Tagging_Trams_in_Germany#Fahrsignale_(F)) in different optical representation. I wouldnt mind if the DE-BSVG version which is basically a single round lamp would be an "A" instead as its the meaning that counts for me. So it would be nice for me (?) to add the PT_priority tag as well.
And I (!) wouldnt mind as well whether its on top or at the bottom, but if its simple done, why not...

2024-12-12 00:13 UTC, closed without merging