render signal_box at zoom 11/12 as point w/o text
OpenRailwayMap/OpenRailwayMap-CartoCSS pull request #63
Opened 2022-01-06 09:25 UTC by bjoernma

This PR resolves issue #9 . I dont think that it's necessary to have text as it would be crowded on the map.

2022-02-28 12:08 UTC, Nakaner requested changes

2022-02-28 12:08 UTC, Nakaner commented on signal_boxes.mss
> +    marker-width: @signal_box_size_z16;
Carto error:

`Error: signal_boxes.mss:24:18 variable @signal_box_size_z16 is undefined`

2022-10-23 11:13 UTC, DerDakon commented
@bjoernma what about the carto error reported above?

2022-10-23 11:59 UTC, bjoernma commented
I cant see why I wanted to change the size at z16 as well, but so the error should be gone.

2022-10-23 12:02 UTC, DerDakon approved these changes

2022-10-23 13:21 UTC, Nakaner commented
Rendering results after my patch:

Zoom level 11, Maschen Rbf:

![maschen-z11](https://user-images.githubusercontent.com/3611273/197394655-cb2ee47e-3832-4f39-b28c-ac9f6d566601.png)

Zoom level 12, Maschen Rbf:

![maschen-z12](https://user-images.githubusercontent.com/3611273/197394657-0b685392-7c1c-464e-8b5d-68fd764e1af3.png)

2022-10-23 13:22 UTC, Nakaner approved these changes

2022-10-23 16:12 UTC, DerDakon commented
This has been merged, no idea why the web interface doesn't get it.

2022-10-23 16:12 UTC, closed without merging