Added code to display abandoned:name or razed:name when available for…
OpenRailwayMap/OpenRailwayMap-CartoCSS pull request #66
Opened 2022-02-22 18:20 UTC by JonathanBittner

… abandoned/razed railroads. This will override the mdoern highway or rail trail name
Fixes OpenRailwayMap/OpenRailwayMap-CartoCSS#44

2022-02-22 22:48 UTC, Nakaner commented
Thank you for your contribution. Looks good at the first glance. I will have to test this before I push the "approve" button.

2022-02-23 14:28 UTC, JonathanBittner commented
Some examples/test cases for you:
Name "Columbia Trail" abandoned:name "High Bridge Branch" https://openrailwaymap.org/?style=standard&lat=40.75231246487251&lon=-74.8188042640686&zoom=15
Name "North Shore Rail Trail" abandoned:name "Wading River Branch" https://openrailwaymap.org/?style=standard&lat=40.75231246487251&lon=-74.8188042640686&zoom=15

2022-02-28 12:05 UTC, Nakaner approved these changes

2022-02-28 17:44 UTC, JonathanBittner commented
Thank you for approving my change. Is there anything I need to do to close this out. I'm still a GitHub newbie.

2022-02-28 19:17 UTC, Nakaner commented
@JonathanBittner You don't have to do anything now. Otherwise I would have choosen "request changes". Another maintainer will merge this pull request.

2022-03-01 16:03 UTC, DerDakon requested changes
Please remove the 2 bogus spaces and split the commit message: add 2 newlines after the first sentence so the first sentence will become the "title" of the commit and the second sentence is just additional text. Please also fix the typo ("mdoern") in the second sentence.

2022-03-01 16:03 UTC, DerDakon commented on standard.mml
> +                CASE
please remove the whitespace at the end of the line

2022-03-02 15:17 UTC, DerDakon approved these changes

2022-03-02 15:17 UTC, merged